general_settings: 
  completion_model: "Pro/deepseek-ai/DeepSeek-R1"  # default model for chat/completion
  embedding_model: "BAAI/bge-m3"                   # default model for embeddings

model_list:
  # siliconflow提供商的模型配置
  - model_name: "Pro/deepseek-ai/DeepSeek-R1"
    litellm_params:
      model: "custom/completion"
      api_key: "sk-bmutyiebgsnrujeozzmwjbawwuxodmxfazethbdvfkturovv"
      api_base: "http://api.siliconflow.cn/v1/chat/completions"
  
  - model_name: "Pro/deepseek-ai/DeepSeek-V3"
    litellm_params:
      model: "custom/completion"
      api_key: "sk-bmutyiebgsnrujeozzmwjbawwuxodmxfazethbdvfkturovv"
      api_base: "http://api.siliconflow.cn/v1/chat/completions"
  
  - model_name: "Qwen/Qwen2.5-7B-Instruct"
    litellm_params:
      model: "custom/completion"
      api_key: "sk-bmutyiebgsnrujeozzmwjbawwuxodmxfazethbdvfkturovv"
      api_base: "http://api.siliconflow.cn/v1/chat/completions"
  
  # 山西提供商的模型配置
  - model_name: "222"
    litellm_params:
      model: "custom/completion"
      api_key: "sk-abc123def456ghi789jkl012mno345pq"
      api_base: "http://36.141.21.137:9081/v1/chat/completions"
  
  # 阿里百炼提供商的模型配置
  - model_name: "qwq-32b"
    litellm_params:
      model: "custom/completion"
      api_key: "sk-50df05e9a3f44fae80765fa045c22435"
      api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
  
  # embeddings models 配置
  - model_name: "BAAI/bge-m3"
    litellm_params:
      model: "custom/embedding"
      api_key: "sk-bmutyiebgsnrujeozzmwjbawwuxodmxfazethbdvfkturovv"
      api_base: "http://api.siliconflow.cn/v1/embeddings"

router_settings:
  routing_strategy: "simple-shuffle"